language: java

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

  branches:
    only:
      - 2.0.x
      - 2.1.x

script: ./gradlew clean build